# This is a basic workflow to help you get started with Actions

name: dev workflow

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # services required by the test
    services:
      planetscale:
        image: vitess/vttestserver:mysql80
        env:
          KEYSPACES: test
          NUM_SHARDS: 2
          FOREIGN_KEY_MODE: disallow
          PLANNER_VERSION: Gen4Fallback
        ports:
          - 33577:33577

    # The type of runner that the job will run on
    strategy:
      matrix:
        python-versions: ['^3.7.x', '^3.8.x', '3.9.x', '^3.10.x']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libssl1.1 libssl1.1=1.1.1f-1ubuntu2 libssl-dev libmysqlclient-dev
          python -m pip install --upgrade pip
          pip install poetry tox tox-gh-actions

      - name: test with tox
        run:
          tox
